export enum ColumnType {
    Text = "Text",
    Number = "Number",
    MultiChoice = "MultiChoice",
    Boolean = "Boolean",
    DateTime = "DateTime",
    Currency = "Currency",
    URL = "URL",
    Lookup = "Lookup",
    User = "User",
    Email = "Email",
    Note = "Note",
    Image = "Image",
    Choice = "Choice",
    Calculated = "Calculated",
    Guid = "Guid",
    Taxonomy = "TaxonomyFieldType",
    Rating = "Rating",
    Location = "Location",
    ModStat = "ModStat",
    File = "File",
    ThreadIndex = "ThreadIndex",
    Threading = "Threading",
    InfowiseAssociated = "Lookup",
  }