import { ColumnType } from "./coulmn";

export const listDefinitions = {
    lists: [
        {
            name: "Application",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "ApplicationName", internalName: "ApplicationName", columnType: ColumnType.Text },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified Byr", internalName: "Editor", columnType: ColumnType.User },

            ],
        },
        {
            name: "Template",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "TemplateName", internalName: "TemplateName", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified Byr", internalName: "Editor", columnType: ColumnType.User },

            ],
        },
        {
            name: "Project",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },
                { columnName: "Actual_End_Date", internalName: 'Actual_End_Date', columnType: ColumnType.DateTime },
                { columnName: "Actual_Start_Date", internalName: 'Actual_Start_Date', columnType: ColumnType.DateTime },
                { columnName: "Description", internalName: 'Description', columnType: ColumnType.Text },
                { columnName: "Name", internalName: 'Name', columnType: ColumnType.Text },
                { columnName: "Planned_End_Date", internalName: 'Planned_End_Date', columnType: ColumnType.DateTime },
                { columnName: "Planned_Start_Date", internalName: 'Planned_Start_Date', columnType: ColumnType.DateTime },
                {
                    columnName: "Status",
                    internalName: 'Status',
                    columnType: ColumnType.Choice,
                    choices: [
                        "New",
                        "In Progress",
                        "On Hold",
                        "Cancelled",
                        "Completed",
                        "In Review",
                    ],
                },
                { columnName: "Budget", internalName: 'Budget', columnType: ColumnType.Currency },
                {
                    columnName: "ProjectType",
                    internalName: 'ProjectType',
                    columnType: ColumnType.Choice,
                    choices: [
                        "Construction",
                        "Software Development",
                        "Water and Irrigation",
                    ],
                },

            ],
        },
        {
            name: "Milestone",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "Modified Date", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created Date", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Actual_End_Date", internalName: "Actual_End_Date", columnType: ColumnType.DateTime },
                { columnName: "Actual_Start_Date", internalName: "Actual_Start_Date", columnType: ColumnType.DateTime },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "Name", internalName: "Name", columnType: ColumnType.Text },
                { columnName: "Planned_End_Date", internalName: "Planned_End_Date", columnType: ColumnType.DateTime },
                { columnName: "Planned_Start_Date", internalName: "Planned_Start_Date", columnType: ColumnType.DateTime },

                {
                    columnName: "Status",
                    internalName: "Status",
                    columnType: ColumnType.Choice,
                    choices: ["New", "On Hold", "In Progress", "Cancelled", "In Review", "Completed"],
                },

                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                { columnName: "EstimatePercentage", internalName: "EstimatePercentage", columnType: ColumnType.Number },
                { columnName: "PercentageOfCompiletion", internalName: "PercentageOfCompiletion", columnType: ColumnType.Number },
                {
                    columnName: "Project",
                    internalName: 'Project',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                { columnName: "Project_Name", internalName: 'Project_Name', columnType: ColumnType.Text },
                { columnName: "Language", internalName: 'Language', columnType: ColumnType.Text },
                { columnName: "Completion_Date", internalName: 'Completion_Date', columnType: ColumnType.DateTime },
                { columnName: "DelayNotified", internalName: 'DelayNotified', columnType: ColumnType.Boolean },
                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "Consultant",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "Name", internalName: "Name", columnType: ColumnType.Text },


                {
                    columnName: "Industry",
                    internalName: "Industry",
                    columnType: ColumnType.Choice,
                    choices: ["Construction", "IT", "Health"],
                },


                { columnName: "Phone", internalName: "Phone", columnType: ColumnType.Text },
                { columnName: "Email", internalName: "Email", columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },

            ],
        },
        {
            name: "Contractor",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Name", internalName: "Name", columnType: ColumnType.Text },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                {
                    columnName: "Industry",
                    internalName: "Industry",
                    columnType: ColumnType.Choice,
                    choices: ["IT", "Health", "Construction"],
                },
                { columnName: "Phone", internalName: "Phone", columnType: ColumnType.Text },
                { columnName: "Email", internalName: "Email", columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "StakeHolder",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "Phone", internalName: "Phone", columnType: ColumnType.Text },
                { columnName: "Email", internalName: "Email", columnType: ColumnType.Text },
                {
                    columnName: "Industry",
                    internalName: "Industry",
                    columnType: ColumnType.Choice,
                    choices: ["Construction", "IT", "Health"],
                },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },

            ],
        },
        {
            name: "Task",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                { columnName: "Name", internalName: "Name", columnType: ColumnType.Text },
                { columnName: "Actual_End_Date", internalName: "Actual_End_Date", columnType: ColumnType.DateTime },
                { columnName: "Actual_Start_Date", internalName: "Actual_Start_Date", columnType: ColumnType.DateTime },
                { columnName: "Planned_End_Date", internalName: "Planned_End_Date", columnType: ColumnType.DateTime },
                { columnName: "Planned_Start_Date", internalName: "Planned_Start_Date", columnType: ColumnType.DateTime },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                {
                    columnName: "Priority",
                    internalName: 'Priority',
                    columnType: ColumnType.Choice,
                    choices: [
                        "High",
                        "Low",
                        "Medium",
                    ],
                },
                {
                    columnName: "Status",
                    internalName: "Status",
                    columnType: ColumnType.Choice,
                    choices: ["New", "On Hold", "In Progress", "Cancelled", "In Review", "Completed"],
                },
                { columnName: "Owner", internalName: 'Owner', columnType: ColumnType.User },
                { columnName: "AssignedTo", internalName: 'AssignedTo', columnType: ColumnType.User },
                { columnName: "PercentageOfComplation", internalName: 'PercentageOfComplation', columnType: ColumnType.Number },
                {
                    columnName: "Milestone",
                    internalName: 'Milestone',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Milestone",
                },
                {
                    columnName: "Project",
                    internalName: 'Project',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                {
                    columnName: "ParentTask",
                    internalName: 'ParentTask',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "PredecessorTask",
                    internalName: 'PredecessorTask',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Task",
                },
                { columnName: "Task_Status", internalName: 'Task_Status', columnType: ColumnType.Number },
                { columnName: "Assigned_User", internalName: 'Assigned_User', columnType: ColumnType.Text },
                { columnName: "Project_Name", internalName: 'Project_Name', columnType: ColumnType.Text },
                { columnName: "Milestone_Name", internalName: 'Milestone_Name', columnType: ColumnType.Text },
                { columnName: "Language", internalName: 'Language', columnType: ColumnType.Text },
                { columnName: "Compilation_Date", internalName: 'Compilation_Date', columnType: ColumnType.DateTime },
                { columnName: "EstimatePercentage", internalName: 'EstimatePercentage', columnType: ColumnType.Number },
                { columnName: "DelayNotified", internalName: 'elayNotified', columnType: ColumnType.Boolean },

                { columnName: "Modified Date", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created Date", internalName: 'Created', columnType: ColumnType.DateTime },

                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "QualityMeasurement",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "MinValue", internalName: 'MinValue', columnType: ColumnType.Number },
                { columnName: "MaxValue", internalName: 'MaxValue', columnType: ColumnType.Number },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "Measurement", internalName: "Measurment", columnType: ColumnType.Text },

                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },

                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "TaskQuality",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                {
                    columnName: "Project:ID",
                    internalName: "Project_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "id",
                    lookupListName: "Project",
                },
                {
                    columnName: "Project:Name",
                    internalName: "Project_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "MileStone",
                    internalName: "MileStone",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Milestone",
                },
                {
                    columnName: "MileStone:ID",
                    internalName: "MileStone_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Milestone",

                },
                {
                    columnName: "MileStone:Name",
                    internalName: "MileStone_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Task",
                },
                {
                    columnName: "Task",
                    internalName: "Task",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Task",
                },
                {
                    columnName: "Task:ID",
                    internalName: "Task_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Task",

                },
                {
                    columnName: "Task:Name",
                    internalName: "Task_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Task",
                },
                { columnName: "QualityTitle", internalName: "QualityTitle", columnType: ColumnType.Text },
                { columnName: "ExpectedValue", internalName: "ExpectedValue", columnType: ColumnType.Text },
                { columnName: "CompletedTask", internalName: "CompletedTask", columnType: ColumnType.Number },
                {
                    columnName: "Status",
                    internalName: "Status",
                    columnType: ColumnType.Choice,
                    choices: ["New", "On Hold", "In Progress", "Cancelled"],
                },
                { columnName: "Value", internalName: "Value", columnType: ColumnType.Number },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Number },
                {
                    columnName: "QualityMeasurement",
                    internalName: "QualityMeasurement",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Title",
                    lookupListName: "QualityMeasurement",
                },
                {
                    columnName: "QualityMeasurement:Title",
                    internalName: "QualityMeasurement_x003a_Title",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Title",
                    lookupListName: "QualityMeasurement",
                },
                {
                    columnName: "QualityMeasurement:Measurement",
                    internalName: "QualityMeasurement_x003a_Measurement",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Measurement",
                    lookupListName: "QualityMeasurement",
                },
                {
                    columnName: "QualityMeasurement:ID",
                    internalName: "QualityMeasurement_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "QualityMeasurement",
                },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "Permissions",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "PermissionName", internalName: "PermissionName", columnType: ColumnType.Text },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },

            ],
        },
        {
            name: "PageResource",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "PageName", internalName: 'PageName', columnType: ColumnType.Text },
                { columnName: "Code", internalName: 'Code', columnType: ColumnType.Text },
                { columnName: "Description", internalName: 'Description', columnType: ColumnType.Text },
                { columnName: "SystemName", internalName: 'SystemName', columnType: ColumnType.Text },
                { columnName: "IsActive", internalName: 'IsActive', columnType: ColumnType.Boolean },
                {
                    columnName: "Application",
                    internalName: 'Application',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Application",
                },
                {
                    columnName: "Application:Title",
                    internalName: 'Application_x003a_Title',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Title",
                    lookupListName: "Application",
                },
                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },

            ],
        },
        {
            name: "Role",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "RoleName", internalName: "RoleName", columnType: ColumnType.Text },
                { columnName: "RoleType", internalName: "RoleType", columnType: ColumnType.Text },
                { columnName: "IsActive", internalName: "IsActive", columnType: ColumnType.Boolean },
                { columnName: "ReadOnly", internalName: "ReadOnly", columnType: ColumnType.Boolean },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "RoleResource",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                {
                    columnName: "PageResource",
                    internalName: "PageResource",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "PageResource",
                },
                {
                    columnName: "PageResource:PageName",
                    internalName: "PageResource_x003a_PageName",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "PageName",
                    lookupListName: "PageResource",
                },
                {
                    columnName: "Role",
                    internalName: "Role",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Role",
                },
                {
                    columnName: "Role:RoleName",
                    internalName: "Role_x003a_RoleName",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "RoleName",
                    lookupListName: "Role",
                },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },

            ],
        },
        {
            name: "Issue",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "Issue", internalName: "Issue", columnType: ColumnType.Text },
                {
                    columnName: "Priority",
                    internalName: "Priority",
                    columnType: ColumnType.Choice,
                    choices: ["Urgent", "High", "Medium", "Low"],
                },
                {
                    columnName: "Status",
                    internalName: "Status",
                    columnType: ColumnType.Choice,
                    choices: ["Closed", "Not Started", "In Progress", "Closed"],
                },
                { columnName: "OpenedOn", internalName: "OpenedOn", columnType: ColumnType.DateTime },
                { columnName: "ClosedOn", internalName: "ClosedOn", columnType: ColumnType.DateTime },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "Project:ID",
                    internalName: "Project_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "id",
                    lookupListName: "Project",
                },
                {
                    columnName: "Project:Name",
                    internalName: "Project_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                {
                    columnName: "Category",
                    internalName: "Category",
                    columnType: ColumnType.Choice,
                    choices: ["Environmental", "Organizational", "Internal", "External", "Technical", "Legal"],
                },
                { columnName: "Name", internalName: "Name", columnType: ColumnType.Text },
                { columnName: "Solution", internalName: "Solution", columnType: ColumnType.Text },
                {
                    columnName: "Response",
                    internalName: "Response",
                    columnType: ColumnType.Choice,
                    choices: ["Closed", "Not Started", "In Progress", "Closed"],
                },
                { columnName: "Description_PM", internalName: "Description_PM", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },

        {
            name: "MileStoneComments",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                {
                    columnName: "MileStone",
                    internalName: "MileStone",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Milestone",
                },
                {
                    columnName: "MileStone:ID",
                    internalName: "MileStone_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Milestone",

                },
                {
                    columnName: "MileStone:Name",
                    internalName: "MileStone_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Milestone",
                },
                { columnName: "Comments", internalName: "Comments", columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "MilestoneTemplate",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "MilestoneName", internalName: 'MilestoneName', columnType: ColumnType.Text },
                { columnName: "EstimatePercentage", internalName: 'EstimatePercentage', columnType: ColumnType.Number },
                { columnName: "EstimateDuration", internalName: 'EstimateDuration', columnType: ColumnType.Number },
                {
                    columnName: "Template",
                    internalName: 'Template',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Template",
                },
                {
                    columnName: "Template:TemplateName",
                    internalName: 'Template_x003a_TemplateName',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "TemplateName",
                    lookupListName: "Template",
                },
                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },


            ],
        },
        {
            name: "Notification",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "ExpiredDate", internalName: "ExpiredDate", columnType: ColumnType.DateTime },
                { columnName: "To", internalName: "To", columnType: ColumnType.User },
                { columnName: "IsRead", internalName: "IsRead", columnType: ColumnType.Boolean },
                { columnName: "IsActive", internalName: "IsActive", columnType: ColumnType.Boolean },
                { columnName: "Body", internalName: "Body", columnType: ColumnType.Text },
                { columnName: "Url", internalName: "Url", columnType: ColumnType.URL },
                {
                    columnName: "Notification_Type",
                    internalName: "Notification_Type",
                    columnType: ColumnType.Choice,
                    choices: ["Info", "Success", "Warning", "Error"],
                },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "ProjectChanges",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                {
                    columnName: "ChangeType",
                    internalName: "ChangeType",
                    columnType: ColumnType.Choice,
                    choices: ["Budget", "Time", "Scope"],
                },
                { columnName: "Amount", columnType: ColumnType.Text },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },

            ],
        },
        {
            name: "ProjectComments",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "Comments", internalName: 'Comments', columnType: ColumnType.Text },
                {
                    columnName: "Project:ID",
                    internalName: 'Project_x003a_ID',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                {
                    columnName: "Project:Name",
                    internalName: 'Project_x003a_Name',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                { columnName: "IsDeleted", internalName: 'IsDeleted', columnType: ColumnType.Boolean },
                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },

            ],
        },
        {
            name: "ProjectConsultant",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                {
                    columnName: "Consultant",
                    internalName: "Consultant",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Consultant",
                },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                { columnName: "Industry", internalName: "Industry", columnType: ColumnType.Text },
                {
                    columnName: "Project:Name",
                    internalName: "Project_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "Consultant:Title",
                    internalName: "Consultant_x003a_Title",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Title",
                    lookupListName: "Consultant",
                },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "ProjectContractor",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },
                { columnName: "IsDeleted", internalName: 'IsDeleted', columnType: ColumnType.Boolean },
                {
                    columnName: "Project",
                    internalName: 'Project',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "Contractor",
                    internalName: 'Contractor',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Contractor",
                },
                { columnName: "Industry", internalName: 'Industry', columnType: ColumnType.Text },
                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "ProjectExtension",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "ExtensionBudget", internalName: "ExtensionBudget", columnType: ColumnType.Number },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                {
                    columnName: "Project:Name",
                    internalName: "Project_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",

                },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                { columnName: "ProjectExtensionDeadline", internalName: "ProjectExtensionDeadline", columnType: ColumnType.DateTime },
                { columnName: "SignificantChangeInActivities", internalName: "SignificantChangeInActivities", columnType: ColumnType.Boolean },
                { columnName: "otherRevision", internalName: "otherRevision", columnType: ColumnType.Text },
                { columnName: "insecurity", internalName: "insecurity", columnType: ColumnType.Boolean },
                { columnName: "programmaticDelays", internalName: "programmaticDelays", columnType: ColumnType.Boolean },
                { columnName: "recruitmentDelays", internalName: "recruitmentDelays", columnType: ColumnType.Boolean },
                { columnName: "delaysInDisbursementOfPayment", internalName: "delaysInDisbursementOfPayment", columnType: ColumnType.Boolean },
                { columnName: "delaysInFinalizingTheAgreement", internalName: "delaysInFinalizingTheAgreement", columnType: ColumnType.Boolean },
                { columnName: "ProcurementDelays", internalName: "ProcurementDelays", columnType: ColumnType.Boolean },
                { columnName: "internalAdminDelays", internalName: "internalAdminDelays", columnType: ColumnType.Boolean },
                { columnName: "OtherReasonProjectExtension", internalName: "OtherReasonProjectExtension", columnType: ColumnType.Text },
                { columnName: "NumberOfMonthsRequired", internalName: "NumberOfMonthsRequired", columnType: ColumnType.Number },
                { columnName: "NewProjectEndDate", internalName: "NewProjectEndDate", columnType: ColumnType.DateTime },
                { columnName: "NewBudgetsRequired", internalName: "NewBudgetsRequired", columnType: ColumnType.Currency },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "ProjectInitiation",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "Phone", internalName: "Phone", columnType: ColumnType.Text },
                { columnName: "Sponsor", internalName: "Sponsor", columnType: ColumnType.Text },
                { columnName: "Customer", internalName: "Customer", columnType: ColumnType.Text },
                { columnName: "Objective", internalName: "Objective", columnType: ColumnType.Text },
                { columnName: "Deliverables", internalName: "Deliverables", columnType: ColumnType.Text },
                { columnName: "Comments", internalName: "Comments", columnType: ColumnType.Text },
                { columnName: "Budget", internalName: "Budget", columnType: ColumnType.Number },
                { columnName: "IsDeleted", internalName: 'IsDeleted', columnType: ColumnType.Boolean },

                { columnName: "Organization", internalName: "Organization", columnType: ColumnType.Text },
                { columnName: "ProjectStartDate", internalName: "ProjectStartDate", columnType: ColumnType.DateTime },
                { columnName: "ProjectDate", internalName: 'ProjectDate', columnType: ColumnType.DateTime },

                {
                    columnName: "Language",
                    internalName: 'Language',
                    columnType: ColumnType.Choice,
                    choices: ["Amharic", "English"],
                },
                { columnName: "ProjectEndDate", internalName: 'ProjectEndDate', columnType: ColumnType.DateTime },
                { columnName: "ProjectLanguage", internalName: 'ProjectLanguage', columnType: ColumnType.Text },
                { columnName: "EstimatedBudget", internalName: 'EstimatedBudget', columnType: ColumnType.Number },
                { columnName: "Department", internalName: 'Department', columnType: ColumnType.DateTime },

                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },


                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "ProjectSponsor",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },
                { columnName: "IsDeleted", internalName: 'IsDeleted', columnType: ColumnType.Boolean },
                { columnName: "Sponsor", internalName: "Sponsor", columnType: ColumnType.Text },
                {
                    columnName: "Project",
                    internalName: 'Project',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "Project:Name",
                    internalName: 'Project_x003a_Name',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },

                { columnName: "Industry", internalName: 'Industry', columnType: ColumnType.Text },
                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "ProjectOwners",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "CompanyName", internalName: "companyName", columnType: ColumnType.Text },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },

            ],
        },
        {
            name: "ProjectTeamMembers",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "Member", internalName: 'Member', columnType: ColumnType.User },
                { columnName: "Role", internalName: 'Role', columnType: ColumnType.Text },
                { columnName: "FullName", internalName: 'FullName', columnType: ColumnType.Text },

                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },
                { columnName: "IsDeleted", internalName: 'IsDeleted', columnType: ColumnType.Boolean },
                {
                    columnName: "Project",
                    internalName: 'Project',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "Project:Name",
                    internalName: 'Project_x003a_Name',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },


                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "ProjectStakeholder",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                {
                    columnName: "StakeHolder",
                    internalName: "StakeHolder",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "StakeHolder",
                },
                {
                    columnName: "Project:Name",
                    internalName: "Project_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "Stakeholder:Title",
                    internalName: "Stakeholder_x003a_Title",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Title",
                    lookupListName: "StakeHolder",
                },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "QualityCheckList",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                {
                    columnName: "Project:ID",
                    internalName: "Project_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "id",
                    lookupListName: "	Project",
                },
                {
                    columnName: "Project:Name",
                    internalName: "Project_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "MileStone",
                    internalName: "MileStone",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Milestone",
                },
                {
                    columnName: "MileStone:ID",
                    internalName: "MileStone_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Milestone",

                },
                {
                    columnName: "MileStone:Name",
                    internalName: "MileStone_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Task",
                },
                {
                    columnName: "Task",
                    internalName: "Task",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Task",
                },
                {
                    columnName: "Task:ID",
                    internalName: "Task_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Task",

                },
                {
                    columnName: "Task:Name",
                    internalName: "Task_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Task",
                },
                { columnName: "CheckListName", internalName: "CheckListName", columnType: ColumnType.Text },
                { columnName: "CheckListAnswer", internalName: "CheckListAnswer", columnType: ColumnType.Boolean },
                {
                    columnName: "TaskQuality",
                    internalName: "TaskQuality",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Title",
                    lookupListName: "TaskQuality",
                },
                {
                    columnName: "TaskQuality:QualityTitle",
                    internalName: "TaskQuality_x003a_QualityTitle",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "QualityTitle",
                    lookupListName: "TaskQuality",

                },
                {
                    columnName: "TaskQuality:ID",
                    internalName: "TaskQuality_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "TaskQuality",
                },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "Resource",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },

                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "Name", internalName: "Name", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },

                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "QualityQuestions",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "QName", internalName: "QName", columnType: ColumnType.Text },
                {
                    columnName: "MileStone",
                    internalName: "MileStone",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Milestone",
                },
                {
                    columnName: "MileStone:ID",
                    internalName: "MileStone_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Milestone",

                },
                {
                    columnName: "MileStone:Name",
                    internalName: "MileStone_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Task",
                },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                {
                    columnName: "Project:ID",
                    internalName: "Project_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "id",
                    lookupListName: "	Project",
                },
                {
                    columnName: "Project:Name",
                    internalName: "Project_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "Task",
                    internalName: "Task",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Task",
                },
                {
                    columnName: "Task:ID",
                    internalName: "Task_x003a_ID",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Task",

                },
                {
                    columnName: "Task:Name",
                    internalName: "Task_x003a_Name",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Task",
                },
                { columnName: "QualityQuestion", internalName: "QualityQuestion", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "Risk",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },

                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                { columnName: "Name", internalName: "Name", columnType: ColumnType.Text },
                {
                    columnName: "Level",
                    internalName: 'Level',
                    columnType: ColumnType.Choice,
                    choices: [
                        'Low',
                        'Moderate',
                        'High'
                    ],
                },
                {
                    columnName: "Status",
                    internalName: 'Status',
                    columnType: ColumnType.Choice,
                    choices: [
                        'Identified',
                        'Assessed',
                        'Controlled',
                        'Closed'
                    ],
                },
                {
                    columnName: "Catagory",
                    internalName: 'Catagory',
                    columnType: ColumnType.Choice,
                    choices: [
                        'Environmental',
                        'Organizational',
                        'Internal',
                        'External',
                        'Technical',
                        'Legal'

                    ],
                },
                {
                    columnName: "Probability",
                    internalName: 'Probability',
                    columnType: ColumnType.Choice,
                    choices: [
                        'Urgent',
                        'High',
                        'Medium',
                        'Low',
                    ],
                },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                {
                    columnName: "Response",
                    internalName: 'Response',
                    columnType: ColumnType.Choice,
                    choices: [
                        'Avoid',
                        'Mitigate',
                        'Transfer',
                        'Accept',

                    ],
                },
                { columnName: "Solution", internalName: 'Solution', columnType: ColumnType.Text },
                {
                    columnName: "Project",
                    internalName: 'Project',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Project",
                },
                {
                    columnName: "Assignee",
                    internalName: "Assignee",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Name",
                    lookupListName: "Contractor",
                },
                { columnName: "Issue", internalName: 'Issue', columnType: ColumnType.Text },
                {
                    columnName: "Priority",
                    internalName: 'Priority',
                    columnType: ColumnType.Choice,
                    choices: [
                        "High",
                        "Low",
                        "Medium",
                    ],
                },
                { columnName: "ImpactOfRisk", internalName: 'ImpactOfRisk', columnType: ColumnType.Text },
                { columnName: "Mitigation Action", internalName: 'MitigatonAction', columnType: ColumnType.Text },
                { columnName: "Modified Date", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created Date", internalName: 'Created', columnType: ColumnType.DateTime },

                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "Resources",
            columns: [
                { columnName: "Title", internalName: "Title", columnType: ColumnType.Text },
                { columnName: "Modified", internalName: "Modified", columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: "Created", columnType: ColumnType.DateTime },
                {
                    columnName: "Project",
                    internalName: "Project",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },
                { columnName: "Name", internalName: "Name", columnType: ColumnType.Text },
                { columnName: "Quantity", internalName: "Quantity", columnType: ColumnType.Text },
                {
                    columnName: "StatusOfAllocation",
                    internalName: "StatusOfAllocation",
                    columnType: ColumnType.Choice,
                    choices: ["Reserved", "Allocated", "To Reserve"],
                },
                {
                    columnName: "LevelofRisk",
                    internalName: "LevelofRisk",
                    columnType: ColumnType.Choice,
                    choices: ["Low", "Medium", "High"],
                },
                { columnName: "DurationRequired", internalName: "DurationRequired", columnType: ColumnType.Number },
                { columnName: "AvailableTimePeriod", internalName: "AvailableTimePeriod", columnType: ColumnType.DateTime },
                {
                    columnName: "ResourceType",
                    internalName: "ResourceType",
                    columnType: ColumnType.Choice,
                    choices: ["Human Resource", "Hardware"],
                },
                { columnName: "Source", internalName: "Source", columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                { columnName: "Cost", internalName: "Cost", columnType: ColumnType.Currency },
                { columnName: "Created By", internalName: "Author", columnType: ColumnType.User },
                { columnName: "Modified By", internalName: "Editor", columnType: ColumnType.User },
            ],
        },
        {
            name: "RolePermission",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                {
                    columnName: "Permission",
                    internalName: "Permission",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Permissions",
                },
                {
                    columnName: "Permission:PermissionName",
                    internalName: "Permission_x003a_PermissionName",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "",//Field Name not Found
                    lookupListName: "Permissions",
                },
                {
                    columnName: "RoleResource",
                    internalName: "RoleResource",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "RoleResource",
                },
                {
                    columnName: "RoleResource:Title",
                    internalName: "RoleResource_x003a_Title",
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "Title",
                    lookupListName: "RoleResource",
                },
                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },

                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },

        {
            name: "Sponser",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "Phone", internalName: "Phone", columnType: ColumnType.Text },
                { columnName: "Email", internalName: "Email", columnType: ColumnType.Text },
                { columnName: "IsDeleted", internalName: "IsDeleted", columnType: ColumnType.Boolean },
                { columnName: "Name", internalName: "Name", columnType: ColumnType.Text },


                {
                    columnName: "Industry",
                    internalName: "Industry",
                    columnType: ColumnType.Choice,
                    choices: ["Construction", "IT", "Health"],
                },
                {
                    columnName: "Project",
                    internalName: 'Project',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Project",
                },
                { columnName: "Description", internalName: "Description", columnType: ColumnType.Text },


                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },

                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "TaskTemplate",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "TaskName", internalName: "TaskName", columnType: ColumnType.Text },
                { columnName: "EstimatePercentage", internalName: 'EstimatePercentage', columnType: ColumnType.Number },
                { columnName: "EstimateDuration", internalName: 'EstimateDuration', columnType: ColumnType.Number },
                {
                    columnName: "MilestoneTemplate",
                    internalName: 'MilestoneTemplate',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "MilestoneTemplate",
                },
                {
                    columnName: "MilestoneTemplate:MilestonName",
                    internalName: 'MilestoneTemplate_x003a_Mileston',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "MilestoneName",
                    lookupListName: "MilestoneTemplate",
                },
                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },

                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },
        {
            name: "UserRole",
            columns: [
                { columnName: "Title", internalName: 'Title', columnType: ColumnType.Text },
                { columnName: "TaskName", internalName: "TaskName", columnType: ColumnType.Text },
                { columnName: "User", internalName: 'User', columnType: ColumnType.User },
                {
                    columnName: "Role",
                    internalName: 'Role',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "ID",
                    lookupListName: "Role",
                },
                {
                    columnName: "Role:RoleName",
                    internalName: 'Role_x003a_RoleName',
                    columnType: ColumnType.Lookup,
                    lookupFieldName: "RoleName",
                    lookupListName: "Role",
                },
                { columnName: "Modified", internalName: 'Modified', columnType: ColumnType.DateTime },
                { columnName: "Created", internalName: 'Created', columnType: ColumnType.DateTime },

                { columnName: "Created By", internalName: 'Author', columnType: ColumnType.User },
                { columnName: "Modified By", internalName: 'Editor', columnType: ColumnType.User },
            ],
        },

    ],
};
export const listDefinitions: any = {
  lists: [
    {
      name: "Documents",
      columns: [
        {
          columnName: "Title",
          internalName: "Title",
          columnType: ColumnType.Text,
        },
        {
          columnName: "ConvertedContent",
          internalName: "ConvertedContent",
          columnType: ColumnType.Text,
        },
        {
          columnName: "FileName",
          internalName: "FileName",
          columnType: ColumnType.Text,
        },
        {
          columnName: "Cost",
          internalName: "Cost",
          columnType: ColumnType.Lookup,
          lookupFieldName: "Name",
          lookupListName: "Cost",
        },
        {
            columnName: "Is_Deleted",
            internalName: "Is_Deleted",
            columnType: ColumnType.Boolean,
          },
          {
            columnName: "Cost:ID",
            internalName: "Cost",
            columnType: ColumnType.Lookup,
            lookupFieldName: "ID",
            lookupListName: "Cost",
          },
        {
          columnName: "Modified",
          internalName: "Modified",
          columnType: ColumnType.DateTime,
        },
        {
          columnName: "Created",
          internalName: "Created",
          columnType: ColumnType.DateTime,
        },
        {
          columnName: "Created By",
          internalName: "Author",
          columnType: ColumnType.User,
        },
        {
          columnName: "Modified By",
          internalName: "Editor",
          columnType: ColumnType.User,
        },
        {
            columnName: "Checked Out To",
            internalName: "CheckoutUser",
            columnType: ColumnType.User,
          },
      ],
    },
    {
      name: "Drop Off Library",
      columns: [
        {
            columnName: "Title",
            internalName: "Title",
            columnType: ColumnType.Text,
          },
          {
            columnName: "ConvertedContent",
            internalName: "ConvertedContent",
            columnType: ColumnType.Text,
          },
    
          {
              columnName: "Original Properties",
              internalName: "Original Properties",
              columnType: ColumnType.Text,
            },
         
          {
            columnName: "Modified",
            internalName: "Modified",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Created",
            internalName: "Created",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Created By",
            internalName: "Author",
            columnType: ColumnType.User,
          },
          {
            columnName: "Modified By",
            internalName: "Editor",
            columnType: ColumnType.User,
          },
          {
              columnName: "Checked Out To",
              internalName: "CheckoutUser",
              columnType: ColumnType.User,
            },
      ],
    },
    {
        name: "ProjectDocuments",
        columns: [
            {
                columnName: "Project",
                internalName: "Project",
                columnType: ColumnType.Lookup,
                lookupFieldName: "ID",
                lookupListName: "Project",
              },
          {
            columnName: "Project:Title",
            internalName: "Project_x003a_Title",
            columnType: ColumnType.Text,
            lookupFieldName: "Title",
            lookupListName: "Project",
          },
          {
            columnName: "ConvertedContent",
            internalName: "ConvertedContent",
            columnType: ColumnType.Text,
          },
          {
            columnName: "FileDescription",
            internalName: "FileDescription",
            columnType: ColumnType.Text,
          },
 
          {
              columnName: "Is_Deleted",
              internalName: "Is_Deleted",
              columnType: ColumnType.Choice,
              choices:[
                'False',
                'True'
              ]
            },
          {
            columnName: "Modified",
            internalName: "Modified",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Created",
            internalName: "Created",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Created By",
            internalName: "Author",
            columnType: ColumnType.User,
          },
          {
            columnName: "Modified By",
            internalName: "Editor",
            columnType: ColumnType.User,
          },
          {
              columnName: "Checked Out To",
              internalName: "CheckoutUser",
              columnType: ColumnType.User,
            },
        ],
      },
      {
        name: "ProjectInitiationDocuments",
        columns: [
            {
                columnName: "ProjectInitiation",
                internalName: "ProjectInitiation",
                columnType: ColumnType.Lookup,
                lookupFieldName: "ID",
                lookupListName: "ProjectInitiation",
              },
          {
            columnName: "ProjectInitiation:Title",
            internalName: "ProjectInitiation_x003a_Title",
            columnType: ColumnType.Lookup,
            lookupFieldName: "Title",
            lookupListName: "ProjectInitiation",
          },
          {
            columnName: "ConvertedContent",
            internalName: "ConvertedContent",
            columnType: ColumnType.Text,
          },
          {
            columnName: "FileDescription",
            internalName: "FileDescription",
            columnType: ColumnType.Text,
          },
 
          {
              columnName: "Is_Deleted",
              internalName: "Is_Deleted",
              columnType: ColumnType.Boolean,
            },
          {
            columnName: "Modified",
            internalName: "Modified",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Created",
            internalName: "Created",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Created By",
            internalName: "Author",
            columnType: ColumnType.User,
          },
          {
            columnName: "Modified By",
            internalName: "Editor",
            columnType: ColumnType.User,
          },
          {
              columnName: "Checked Out To",
              internalName: "CheckoutUser",
              columnType: ColumnType.User,
            },
        ],
      },
      {
        name: "Sites Assets",
        columns: [
          {
            columnName: "ConvertedContent",
            internalName: "ConvertedContent",
            columnType: ColumnType.Text,
          },
          {
            columnName: "Modified",
            internalName: "Modified",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Created",
            internalName: "Created",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Task",
            internalName: "Task",
            columnType: ColumnType.Lookup,
            lookupFieldName: "ID",
            lookupListName: "Task",
          },
          {
            columnName: "Task:ID",
            internalName: "Task_x003a_ID",
            columnType: ColumnType.Lookup,
            lookupFieldName: "ID",
            lookupListName: "Task",
          },
          {
            columnName: "Task:ID",
            internalName: "Task_x003a_Name",
            columnType: ColumnType.Lookup,
            lookupFieldName: "Name",
            lookupListName: "Task",
          },
          {
            columnName: "Created By",
            internalName: "Author",
            columnType: ColumnType.User,
          },
          {
            columnName: "Is_Deleted",
            internalName: "Is_Deleted",
            columnType: ColumnType.Text,
          },
          {
            columnName: "TaskFileName",
            internalName: "TaskFileName",
            columnType: ColumnType.Text,
          },
          {
            columnName: "Modified By",
            internalName: "Editor",
            columnType: ColumnType.User,
          },
          {
              columnName: "Checked Out To",
              internalName: "CheckoutUser",
              columnType: ColumnType.User,
            },
        ],
      },
      {
        name: "TaskDocuments",
        columns: [
          {
            columnName: "ConvertedContent",
            internalName: "ConvertedContent",
            columnType: ColumnType.Text,
          },
          {
            columnName: "FileDescription",
            internalName: "FileDescription",
            columnType: ColumnType.Text,
          },
          {
            columnName: "Modified",
            internalName: "Modified",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Created",
            internalName: "Created",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Created By",
            internalName: "Author",
            columnType: ColumnType.User,
          },
          {
            columnName: "Modified By",
            internalName: "Editor",
            columnType: ColumnType.User,
          },
          {
              columnName: "Checked Out To",
              internalName: "CheckoutUser",
              columnType: ColumnType.User,
            },
        ],
      },
      {
        name: "TaskQualityFile",
        columns: [
          {
            columnName: "ConvertedContent",
            internalName: "ConvertedContent",
            columnType: ColumnType.Text,
          },
          {
            columnName: "FileDescription",
            internalName: "FileDescription",
            columnType: ColumnType.Text,
          },
          {
            columnName: "Modified",
            internalName: "Modified",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Task",
            internalName: "Task",
            columnType: ColumnType.Lookup,
            lookupFieldName: "ID",
            lookupListName: "Task",
          },
          {
            columnName: "Task:ID",
            internalName: "Task_x003a_ID",
            columnType: ColumnType.Lookup,
            lookupFieldName: "ID",
            lookupListName: "Task",
          },
          {
            columnName: "Task:ID",
            internalName: "Task_x003a_Name",
            columnType: ColumnType.Lookup,
            lookupFieldName: "Name",
            lookupListName: "Task",
          },
          {
            columnName: "Created By",
            internalName: "Author",
            columnType: ColumnType.User,
          },
          {
            columnName: "Is_Deleted",
            internalName: "Is_Deleted",
            columnType: ColumnType.Text,
          },
          {
            columnName: "QualityFileName",
            internalName: "QualityFileName",
            columnType: ColumnType.Text,
          },
          {
            columnName: "Created",
            internalName: "Created",
            columnType: ColumnType.DateTime,
          },
          {
            columnName: "Created By",
            internalName: "Author",
            columnType: ColumnType.User,
          },
          {
            columnName: "Modified By",
            internalName: "Editor",
            columnType: ColumnType.User,
          },
          {
              columnName: "Checked Out To",
              internalName: "CheckoutUser",
              columnType: ColumnType.User,
            },
        ],
      },
  ],
};